### ISSUE TITLE
[BUG]: 无法正确响应定时信息

### ISSUE THREAD

**Issue by sherlockHlb** [A-kirami/nonebot-plugin-moyu#12]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

现版本

### 问题描述

无法响应定时信息

### 复现步骤

/摸鱼 8:00
提示已经添加成功
但是8点的时候并没有反应.

### 预期行为

在八点发送图片

**Comment by 3CB3EC** [comment]
大概是因为图片获取速度太慢了，导致定时任务超时，找到这个包的这个文件__init__.py，加一行代码

@driver.on_startup
async def subscribe_jobs():
    for group_id, info in subscribe_list.items():
        scheduler.add_job(
            push_calendar,
            "cron",
            args=[group_id],
            id=f"moyu_calendar_{group_id}",
            replace_existing=True,
            hour=info["hour"],
            minute=info["minute"],
            misfire_grace_time=60  ←增加这一行
        )

这会使定时任务超时时间延长到60秒
