### ISSUE TITLE
[BUG]: 现在获取不到摸鱼日历图片了

### ISSUE THREAD

**Issue by cj1357** [A-kirami/nonebot-plugin-moyu#15]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.3.3

### 问题描述

![}(B{Y67)%XF8EK5~0SEJMY8](https://github.com/A-kirami/nonebot-plugin-moyu/assets/40661342/560d07b2-a492-4895-9667-32ed7fd65de1)
现在每天获取到的都是同一张图片

### 复现步骤

每天获取到的都是同一张图片

**Comment by cj1357** [comment]
又正常了…

**Comment by 360add** [comment]
我也跟你一样，你现在能用吗

**Comment by cj1357** [comment]
> 我也跟你一样，你现在能用吗

最近确实又这样了，只能等了，这个不是插件本身的问题，是api那边数据的问题

**Comment by 360add** [comment]
那肯定是用不了的，跟你发的图一样

**Comment by 360add** [comment]
主要最近60s看世界也用不了，烦人

**Comment by luluxiaoyu** [comment]
又不正常了。。
