### ISSUE TITLE
BUG: 原有API不能返回图片了，改进代码，从API返回的公众号文章地址获取图片

### ISSUE THREAD

**Issue by 3CB3EC** [A-kirami/nonebot-plugin-moyu#20]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

0.3.3

### 问题描述

看了原始代码，图片的获取流程是这样的：
1、调用moyu API，这个API会返回一个JSON数据
2、从返回的JSON数据结构中的content["data"]["img_url"]这个位置获取图片的URL
3、访问这个URL获取图片（这个URL是固定的，正常的话会跳转到当天的图片URL链接）

问题出现在3，现在这个固定的链接已经无法跳转到具体的图片

### 复现步骤

-

### 预期行为

-

### 日志信息

-

### 额外补充

改进了一下代码，将__init__.py文件中同名函数替换为如下内容

```
async def get_calendar() -> bytes:
    async with httpx.AsyncClient(http2=True, follow_redirects=True) as client:
        response = await client.get(
            "https://api.j4u.ink/v1/store/other/proxy/remote/moyu.json"
        )
        if response.is_error:
            raise ValueError(f"摸鱼日历获取失败，错误码：{response.status_code}")
        content = response.json()
        response = await client.get(
            str(content['data']['articles'][-1]['url'])
        )
        if response.is_error:
            raise ValueError(f"摸鱼日历获取失败，错误码：{response.status_code}")

        urls = re.findall(r'data-src="([^"]+)"', response.text[response.text.find('今天你摸鱼了吗？'):])

        image = await client.get(urls[0])
        return image.content
```

原理是从原来API返回的JSON数据中，找到公众号文章地址，去公众号文章里获取图片

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
直接提交一个 PR 吧
