### ISSUE TITLE
摸不了鱼

### ISSUE THREAD

**Issue by ATTomatoo** [A-kirami/nonebot-plugin-moyu#3]
API接口链接已经更新，但依旧无法摸
![6BGWPHUW3X`ZZC)8GKHCL](https://user-images.githubusercontent.com/93612024/174024596-27750dc2-c35a-4258-b1bf-6110847eeeda.png)
鱼

**Comment by ATTomatoo** [comment]
![0GIP}PIU{94~%XWPN8DU828](https://user-images.githubusercontent.com/93612024/174025098-bda0983a-bdd1-4a40-ac71-19aa3c2080a8.png)
文件的接口API有更新过

**Comment by A-kirami** [comment]
已修复此问题，请更新版本到v0.3.0
